services:
  web:
    build: .
    container_name: billstation_auth
    working_dir: /app/backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: billstation_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-billstation}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: billstation_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
